language: python
python:
  - "3.4_with_system_site_packages"
before_install:
  - "sudo apt-get install -qq python-numpy python-scipy"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
script: nosetests

